# Generated by Django 4.2.7 on 2023-12-07 10:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_dbox_rename_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='isFree',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('0e42664c-28d7-4569-a85e-f95205d05056'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('c9a282bd-e657-4c95-af46-32300466dc28'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.category'),
        ),
    ]
