# Generated by Django 4.2.7 on 2023-12-07 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_box_isfree_alter_box_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('e44257cc-7f4e-4c49-8e94-6d73ce6fe8f9'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('02d767cf-51ab-4348-83ab-b7bfd583ae43'), max_length=100, null=True, unique=True),
        ),
    ]
