# Generated by Django 4.2.7 on 2023-12-07 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_box_unique_id_alter_dbox_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('b088c3bf-ca63-47e7-bf4d-b37627252715'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('012b3249-947a-4c78-aff6-8df604408994'), max_length=100, null=True, unique=True),
        ),
    ]
