# Generated by Django 4.2.7 on 2023-12-07 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_box_unique_id_alter_dbox_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('b7c28ba4-0e2c-4aa9-993d-add022144900'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('b2def951-c251-4743-9d74-272e890bf433'), max_length=100, null=True, unique=True),
        ),
    ]
