# Generated by Django 4.2.7 on 2023-12-07 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_box_unique_id_alter_dbox_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('44c893ab-f749-4c5a-b163-d436a146a0ef'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('6bc0b7aa-caec-42b1-b7c0-ee4b73794294'), max_length=100, null=True, unique=True),
        ),
    ]
