# Generated by Django 4.2.7 on 2023-12-07 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_box_unique_id_alter_dbox_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('af4a5fc1-e013-48bf-9c7e-fff7b349190e'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('66a81c2a-d9f9-44ae-aece-e9bfd305d5e9'), max_length=100, null=True, unique=True),
        ),
    ]
