# Generated by Django 4.2.7 on 2023-12-07 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_box_unique_id_alter_dbox_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('1058ca39-b6fa-49ee-bbfa-e4eb8763d92d'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('30adbb9f-bba9-4e14-8e64-f7f4f1dfe255'), max_length=100, null=True, unique=True),
        ),
    ]
