# Generated by Django 4.2.7 on 2023-12-11 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_box_unique_id_alter_dbox_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('a32b576c-fd9b-4868-8f19-cdc32d4d3fdf'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('4be94d93-9cf2-4056-a67b-f7ecbe0228eb'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('f21a9847-0f89-4e0c-9003-4de8ebc97b32'), max_length=100, null=True, unique=True),
        ),
    ]
