# Generated by Django 4.2.7 on 2023-12-11 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_box_unique_id_alter_dbox_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('520840a4-03bf-43e0-8a22-e5cad372c111'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('5825c452-f0b9-4382-8a80-1c0aeb0b36b5'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('4c4aedb1-f5b1-46ba-a88f-5a19a07fc7cc'), max_length=100, null=True, unique=True),
        ),
    ]
