# Generated by Django 4.2.7 on 2023-12-11 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_box_unique_id_alter_dbox_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('b55049ed-7044-47b2-8051-fc100008b82f'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('ededce66-72d5-4c62-9e35-b2f2495c0c57'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('b3c5a391-b2eb-4f59-acb3-693f3d28bf7c'), max_length=100, null=True, unique=True),
        ),
    ]
