# Generated by Django 4.2.7 on 2023-12-11 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_user_alter_box_unique_id_alter_dbox_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('fe11099f-660e-4d02-8946-295728126b3e'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('0677ad59-b9d0-440d-b7c8-5ff1870261dd'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('0e6acc28-373d-4b9c-a3c2-0e849ce10108'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nfc_number',
            field=models.CharField(blank=True, default=uuid.UUID('19d7c7f9-4b21-4994-90f3-00661f8811e0'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('f2c83017-be94-4d7d-94eb-170c3add849b'), max_length=100, null=True, unique=True),
        ),
    ]
