# Generated by Django 4.2.7 on 2023-12-11 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_box_unique_id_alter_dbox_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('24c4688f-60bd-4280-abb0-13c8c85a4b02'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('4c2162ca-02ef-4706-b1e7-41f43d8408a3'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('9514eb7b-f8b7-4715-8c5d-242e35aac809'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nfc_number',
            field=models.CharField(blank=True, default=uuid.UUID('4510fb01-9b0d-46d7-af9c-78d7fdd54db1'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='products_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('ddb49497-7a67-4874-9d51-743ea0a030a7'), max_length=100, null=True, unique=True),
        ),
    ]
