# Generated by Django 4.2.7 on 2024-01-05 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_alter_box_unique_id_alter_dbox_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('10b4d4d3-137a-481b-86df-340b78f2a100'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('ee14f64e-5321-4262-a72e-e3423dd9a0ce'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('0b9b2b1f-0e7f-47c2-9fd4-5a19fdb0b600'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nfc_number',
            field=models.CharField(blank=True, default=uuid.UUID('a2b2951a-351e-4279-8654-f04d51a2b85b'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('715d1d84-7586-4ee6-a3a3-a73ea214fc49'), max_length=100, null=True, unique=True),
        ),
    ]
