# Generated by Django 4.2.7 on 2024-01-05 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_box_unique_id_alter_dbox_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('947d8eae-33d5-44ae-b4c9-3b64905f3853'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('894fedc5-224e-40cb-8c18-7c694b801eb5'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('cc3a4a98-d81e-439a-9517-77621442eacc'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nfc_number',
            field=models.CharField(blank=True, default=uuid.UUID('37a9dcf0-d09a-4624-b44c-905649a263d0'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('731e1719-8615-4b61-ab56-21378bcc5e71'), max_length=100, null=True, unique=True),
        ),
    ]
