# Generated by Django 4.2.7 on 2024-01-07 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_box_unique_id_alter_dbox_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unique_ID',
        ),
        migrations.AddField(
            model_name='product',
            name='box_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('38ca6131-6402-42ee-b4e3-c0e6004f06ce'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('bbbd784a-1769-4ebc-8e90-19b4b72938ae'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nfc_number',
            field=models.CharField(blank=True, default=uuid.UUID('2e7e67eb-2230-4afd-a0f2-ceb49a28163b'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('ffb884a0-9bb4-4fae-bd3f-c6fdc1206b76'), max_length=100, null=True, unique=True),
        ),
    ]
