# Generated by Django 4.2.7 on 2024-01-07 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_remove_product_category_remove_product_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_uid',
        ),
        migrations.AlterField(
            model_name='box',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('50e08dbe-de66-4c56-976e-49ba0cc3b5cb'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbox',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('04b2948f-99ae-45ae-b66d-55cb10809cf3'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nfc_number',
            field=models.CharField(blank=True, default=uuid.UUID('e7b5c08f-7c2d-4215-8229-91a7158b2bd7'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_ID',
            field=models.CharField(blank=True, default=uuid.UUID('ecdc4577-7c91-4513-af09-adedf6b799df'), max_length=100, null=True, unique=True),
        ),
    ]
